{% set version = "0.46.2" %}

package:
  name: wheel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wheel/wheel-{{ version }}.tar.gz
  sha256: 3d79e48fde9847618a5a181f3cc35764c349c752e2fe911e65fa17faab9809b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -c "import flit_core.buildapi; flit_core.buildapi.build_wheel('.')" && {{ PYTHON }} -m installer --no-compile-bytecode wheel-*.whl
  entry_points:
    - wheel = wheel._commands:main

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.11,<4
    - python-installer
  run:
    - python >={{ python_min }}
    - packaging >=24.0

test:
  imports:
    - wheel
  commands:
    - pip check
    - wheel --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
