{% set version = "0.45.0" %}

package:
  name: wheel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wheel/wheel-{{ version }}.tar.gz
  sha256: a57353941a3183b3d5365346b567a260a0602a0f8a635926a7dede41b94c674a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -c "import flit_core.buildapi; flit_core.buildapi.build_wheel('.')" && {{ PYTHON }} -m installer --no-compile-bytecode wheel-*.whl
  entry_points:
    - wheel = wheel.cli:main

requirements:
  host:
    - flit-core
    - python >=3.8
    - python-installer
  run:
    - python >=3.8

test:
  imports:
    - wheel
    - wheel.cli
  commands:
    - pip check
    - wheel --help
  requires:
    - pip

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
