{% set version = "0.33.2" %}

package:
  name: wheel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wheel/wheel-{{ version }}.tar.gz
  sha256: 2ef391896c1c6dce2e1f67ac2f371b41fdc2f46a90d3142ec3239419535df1ca

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - wheel = wheel.cli:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - wheel
  commands:
    - wheel --help

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
