{% set name = "wheel" %}
{% set version = "0.31.0" %}
{% set checksum = "1ae8153bed701cb062913b72429bcf854ba824f973735427681882a688cb55ce" %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - wheel = wheel.tool:main

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  imports:
    - wheel
    - wheel.signatures
    - wheel.tool

  commands:
    - wheel --help

  requires:
    - coverage
    - jsonschema
    - pytest
    - pytest-cov

about:
  home: https://bitbucket.org/pypa/wheel/
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
