{% set version = "0.33.5" %}

package:
  name: wheel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wheel/wheel-{{ version }}.tar.gz
  sha256: 0f83c322fbe95b5298aa306e822b273903c8b56c4729fae2a0650cc25a7678b4

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - wheel = wheel.cli:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - wheel
  commands:
    - wheel --help

about:
  home: https://github.com/pypa/wheel
  license: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - mingwandroid
